In [ ]:
import numpy as np

# 🧊 Array Attributes



### (a.ndim, a.size, a.shape, a.dtype)

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [0, 1, 0]])

In [ ]:
np.array([1,2,3,4,5,6,7,8,9,10][0]) # indexing with array

array(1)

In [ ]:
# Return the dimensions of the array
a.ndim # 1D or 2D or 3D

2

In [ ]:
# Returns a tuple showing the size (rows,cols)
a.shape

(4, 3)

In [ ]:
# Returns total number of elements in the array
a.size

12

In [ ]:
# Gives the data type of elements in the array
a.dtype

dtype('int64')

In [ ]:
# Always True
# dimension of array = len((rows,col,...))
a.ndim == len(a.shape)

True

In [ ]:
# Always True
# total no. of items = (no. of rows * no. of cols)
import math
a.size == math.prod(a.shape)

True

In [ ]:
print(np.array(49).ndim)
print(np.array([49]).ndim)

0
1


# 🧊 Conversion

### a.astype(in/float/bool)

In [ ]:
# No a.astype() does not modify the main array.
# It always returns a new array (a copy) with the new data type.

In [ ]:
temp_float = np.array([33.3,34.7,34.6,43.2,45.09])
print(temp_float.dtype)
temp_int = temp_float.astype(int)
print(temp_int.dtype)
print(temp_int)

float64
int64
[33 34 34 43 45]


#  🧊 Creation of Basic Array

### np.zeros(), np.ones(), np.full(), np.empty(), np.arange(), np.linspace()

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(7, dtype=float) # using dtype

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((2,3,5))
# np.zeros(2,3,5) 🚫

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
np.ones((2,4,5,3))

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [ ]:
np.ones(2, dtype=float) # using dtype

array([1., 1.])

Specific value

In [ ]:
np.full(4,7)

array([7, 7, 7, 7])

In [ ]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
# Create an empty array with garbage values(0/1/any other)
np.empty(2)

array([1., 1.])

In [ ]:
np.empty(5,dtype = float) # using (dtype)

array([0., 0., 0., 0., 0.])

In [ ]:
# Creates an array with **evenly spaced** values within a **given range**
# np.arange(start, stop, step)
np.arange(6, dtype = float) # dtype can be used or not

array([0., 1., 2., 3., 4., 5.])

In [ ]:
np.arange(7) #  if 1 item 0 to (item-1)

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
np.arange(2007,2025) # if 2 items start to (stop-1)

array([2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
       2018, 2019, 2020, 2021, 2022, 2023, 2024])

In [ ]:
np.arange(5,15,2) # always exclude stop

array([ 5,  7,  9, 11, 13])

In [ ]:
# np.linspace()
# Creates array between a start and stop on basis of (how many items required)
# diff = (last - first) / (k-1)
# By default (np.linspace) returns values as float64
# By default, the stop value(k) is included in the final array

In [ ]:
# np.linspace(start, stop, num(k)=50, endpoint=True, retstep=False, dtype=None, axis=0)

1 arg

In [ ]:
# np.linspace(5)
# Error 🚫

2 args

In [ ]:
np.linspace(49,147) # no explicitly step(k) provided, so default k = 50

array([ 49.,  51.,  53.,  55.,  57.,  59.,  61.,  63.,  65.,  67.,  69.,
        71.,  73.,  75.,  77.,  79.,  81.,  83.,  85.,  87.,  89.,  91.,
        93.,  95.,  97.,  99., 101., 103., 105., 107., 109., 111., 113.,
       115., 117., 119., 121., 123., 125., 127., 129., 131., 133., 135.,
       137., 139., 141., 143., 145., 147.])

3 args

In [ ]:
np.linspace(5,15,7)

array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        ])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

4 args

In [ ]:
# endpoint either True or False
print(np.linspace(2, 10, 5, True))   # endpoint = True (include 10) [by default]
print(np.linspace(2, 10, 5, False))  # endpoint = False (exclude 10)

[ 2.  4.  6.  8. 10.]
[2.  3.6 5.2 6.8 8.4]


In [ ]:
print(np.linspace(2, 10, 5, True))
# Normal way
# diff = (last - first) / (k-1)

[ 2.  4.  6.  8. 10.]


In [ ]:
print(np.linspace(2, 10, 5, False))
# diff = (last - first) / (k)

[2.  3.6 5.2 6.8 8.4]


5 args

In [ ]:
np.linspace(0, 1, 5, True, True) # returns (array, dtype(k))

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), np.float64(0.25))

In [ ]:
np.linspace(0, 1, 5, False, True) # returns (array, dtype(k))

(array([0. , 0.2, 0.4, 0.6, 0.8]), np.float64(0.2))

In [ ]:
np.linspace(0, 1, 5, True, False) # returns (array) as last is False

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0, 1, 5, False, False)

array([0. , 0.2, 0.4, 0.6, 0.8])

6 args

In [ ]:
np.linspace(0, 10, 5, True, False, int)
# if k is float ----converted----> into int

array([ 0,  2,  5,  7, 10])

# 🧊 Adding

### np.append(), np.insert(), np.concatenate()

In [ ]:
# np.insert(arr, idx, item, axis=None/0/1)

In [ ]:
# does not change the original array
# returns a new  modified array

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
new_arr = np.insert(arr, 5, 10) # insert 10 at 5
print("Original Array:",arr)
print("Modified Array:",new_arr)

Original Array: [1 2 3 4 5 6 7 8 9]
Modified Array: [ 1  2  3  4  5 10  6  7  8  9]


In [ ]:
# np.append(arr,item)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
new_arr = np.append(arr, 10) # insert always at end
print("Original Array:",arr)
print("Modified Array:",new_arr)

Original Array: [1 2 3 4 5 6 7 8 9]
Modified Array: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# np.concatenate(arr,brr)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
brr = np.array([10,20,30,40,50,60,70,80,90])
np.concatenate((arr,brr))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 20, 30, 40, 50, 60, 70, 80,
       90])

# 🧊 Removing

### np.delete()

In [ ]:
# np.delete(arr, index, axis=None)

In [ ]:
# does not change the original array
# returns a new modified array

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
np.delete(arr,0)

array([2, 3, 4, 5, 6, 7, 8, 9])

# 🧊 Sorting

### np.sort() vs a.sort(), np.argsort(), np.lexsort(), np.searchsorted()


np.sort ( )

In [ ]:
# np.sort(a, axis=-1, kind=None, order=None, stable = None/True/False)

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# np.sort() does not change the original array
np.sort(arr) # returns a new array(sorted)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr_2D = np.array([[0,7,4],
                   [8,3,1],
                   [3,1,2]])

In [ ]:
# row wise sorting (default axis = -1)
np.sort(arr_2D)

array([[0, 4, 7],
       [1, 3, 8],
       [1, 2, 3]])

In [ ]:
np.sort(arr_2D, axis = 1) # row wise sorting for 2D Array

array([[0, 4, 7],
       [1, 3, 8],
       [1, 2, 3]])

In [ ]:
np.sort(arr_2D, axis = 0) # coloumn wise sorting

array([[0, 1, 1],
       [3, 3, 2],
       [8, 7, 4]])

In [ ]:
np.sort(arr_2D, axis = None) # Sort as flattened array

array([0, 1, 1, 2, 3, 3, 4, 7, 8])

In [ ]:
np.sort(arr,kind='mergesort') # kind = {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([5,3,1,4,2])
#np.sort(arr, kind='quicksort', stable=True)
# `kind` and `stable` parameters can't be provided 🚫
# at the same time. Use only one of them.

arr.sort ( )

In [ ]:
# arr.sort(axis=-1, kind=None, order=None)

In [ ]:
arr.sort() # just soring happens in arr, not returning
print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>



np.sort( ) vs array_name.sort( )

In [ ]:
# np.sort(arr) : returns a new sorted array
# arr.sort()   : sort the old array
arr = np.array([9,8,7,6,5,4,3,2,1])
print("Before Sorting:",arr)
arr.sort()
print("After Sorting:",arr)


Before Sorting: [9 8 7 6 5 4 3 2 1]
After Sorting: [1 2 3 4 5 6 7 8 9]


np.argsort ( )

In [ ]:
np.argsort(arr) # idx_sorted(10 20 30 40 50)
# Use when you just need to sort a single array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

np.lexsort ( )

In [ ]:
# np.lexsort(key1,key2,key3) ==> “sort by the last key(3) first”
# (Multiple keys) sorting techniue

In [ ]:
names = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'])
ages  = np.array([25,      30,    25,        30,      22,   25])
depts = np.array(['HR',    'IT',  'HR',      'IT',    'HR', 'HR'])

# Keys order: (name, age, dept)
# Primary key = dept, Secondary = age, Tertiary = name

idx = np.lexsort((names, ages, depts))
print(depts[idx])
print(ages[idx])
print(names[idx])

['HR' 'HR' 'HR' 'HR' 'IT' 'IT']
[22 25 25 25 30 30]
['Eve' 'Alice' 'Charlie' 'Frank' 'Bob' 'David']


np.searchsorted ( )

In [ ]:
# array should be previously sorted

In [ ]:
# it does not insert val
# returns index where value to be inserted

In [ ]:
# np.searchsorted(arr, val, side='left', sorted=...)

In [ ]:
# single element
arr = np.array([1, 3, 5, 7, 9])  # sorted array
np.searchsorted(arr, 6)          # element 6 to be inserted at idx 3

np.int64(3)

In [ ]:
# Multiple elements
arr = np.array([2,5,7])
values = np.array([1,3,6]) # list / tuple / array
np.searchsorted(arr, values) # always returns array

array([0, 1, 2])

In [ ]:
# if array is not sorted: can use argsort() & sorter keyword
a = np.array([30, 10, 50, 20, 40])  # unsorted
v = [25, 35]

idx = np.argsort(a)
print("Sorter:", idx)   # [1 3 0 4 2] → positions for [10, 20, 30, 40, 50]

# now searchsorted with 'sorter'
op = np.searchsorted(a, v, sorter=idx)
print(op)   # [2 3]

Sorter: [1 3 0 4 2]
[2 3]


In [ ]:
# "left" or "right" makes no difference when the value is absent

In [ ]:
a = np.array([10, 20, 40, 50, 60])
print(np.searchsorted(a, 55, side='left'))   # 4
print(np.searchsorted(a, 55, side='right'))  # 4

4
4


In [ ]:
# side = 'left'  → insert before the first occurrence of the value
# side = 'right' → insert after the last occurrence of the value

In [ ]:
a = np.array([10, 20, 20, 40, 50])
print(np.searchsorted(a, 20, side='left'))  # 'left'  → before the last 20
print(np.searchsorted(a, 20, side='right')) # 'right' → after the last 20

1
3


np.partition ( )

1. Finding the 'k' smallest or largest elements quickly

In [ ]:
arr = np.array([7, 2, 5, 3, 1, 6, 4])

# 3 smallest elements
k_smallest = np.partition(arr, 3)[:3]
print(k_smallest)  # e.g., [2 1 3]

# 3 largest elements
k_largest = np.partition(arr, -3)[-3:]
print(k_largest)  # e.g., [7 5 6]

[1 2 3]
[5 6 7]


2. Finding median (without sorting)

In [ ]:
arr = np.array([7, 2, 5, 3, 1, 6, 4])
n = len(arr)
median = np.partition(arr, n//2)[n//2]
print(median)  # 4

4


3. Top-k selection in machine learning

#🧊 Concatenate & Split

### np.concatenate(), np.array_split(), np.split(), np.hsplit(), np.vsplit()

np.concatenate( )

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Example 1: Default axis=0 (coloumn-wise)
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))
# [[1 2],
#  [3 4],
#  [5 6]]
print("--------------------------------------")
# Example 2: Concatenate row-wise (axis=1)
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5],
              [6]])
print(np.concatenate((a, b), axis=1))
# [[1 2 5]
#  [3 4 6]]
print("--------------------------------------")
# Example 3: axis=None (flatten + join)
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
print(np.concatenate((a, b), axis=None))
# [1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]
--------------------------------------
[[1 2 5]
 [3 4 6]]
--------------------------------------
[1 2 3 4 5 6]


np.array_split( )

In [ ]:
x = np.arange(8)
# [0,1,2,3,4,5,6,7]
# split into 3 equal parts
np.array_split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

np.split( )

In [ ]:
arr = np.arange(8)
np.split(arr, 4)
# if array cannot be splitted evenly error will be shown

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]

In [ ]:
arr = np.array([1,2,4,7,5,3])
print(np.split(arr,3))
print(np.hsplit(arr,3))

[array([1, 2]), array([4, 7]), array([5, 3])]
[array([1, 2]), array([4, 7]), array([5, 3])]


In [ ]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

# Split into 2 along rows (axis=0)
print(np.split(a, 2, axis=0))

print("-----------------------------------------------")

# Split into 2 along columns (axis=1)
print(np.split(a, 4, axis=1))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
-----------------------------------------------
[array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]]), array([[4],
       [8]])]


np.hsplit( )

In [ ]:
# Equivalent to np.split(a, x, axis=0)

🔑 Key Difference

1D Array:

np.split(arr, x) → splits along axis=0 (the only axis available).

np.hsplit(arr, x) → special case: since there’s no axis=1, it also falls back to axis=0.

***>>> So they behave the same in 1D arrays***

2D Arrays:

np.split( ) → Flexible, you can choose axis=0 (rows) or axis=1 (columns).

np.hsplit( ) → Fixed: only splits along columns (axis=1).

In [ ]:
arr = np.arange(12).reshape(3, 4)
print(arr)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

print(np.hsplit(arr, 2))
# same as np.split(arr, 2, axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


np.vsplit( )

In [ ]:
arr = np.arange(16).reshape(4, 4)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]
#  [12 13 14 15]]
print(np.split(arr,4))
print(np.split(arr,4,axis=0))  # vsplit() in 2D array
print(np.split(arr,4,axis=1))  # hsplit() in 2D array

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [ ]:
c = np.array(([1,2,3],
              [4,5,6],
              [2,0,4]))
np.concatenate(c,axis=None)

array([1, 2, 3, 4, 5, 6, 2, 0, 4])

#🧊 Reshape an Array

### np.reshape()

In [ ]:
arr = np.arange(16)
print(np.reshape(arr,(4,4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
array_1D = np.arange(12)    # [0 1 2 3 4 5 6 7 8 9 10 11]
array_2D = np.reshape(array_1D, (3, 4)) # (row,col)
print("Original:", array_1D)
print("Reshaped (3x4):\n", array_2D)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr = np.arange(12)
# Row Major Representation
new_arr = np.reshape(arr, (3, 4), order='C')
print("Original:", arr)
print("\nReshaped (3x4) with order='C':\n", new_arr)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped (3x4) with order='C':
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr = np.arange(12)
# Column Major Representation
new_arr = np.reshape(arr, (3, 4), order='F')
print("Original:", arr)
print("\nReshaped (3x4) with order='F':\n", new_arr)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped (3x4) with order='F':
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


# 🧊 Indexing and Slicing

### [ : : -1 ]

In [ ]:
# index and slice NumPy arrays as same as Python lists

In [ ]:
data = np.array([0,1,2,3,4,5,6,7,8,9])
print(data[1])
print(data[0:9]) # skip last
print(data[0:10])
print(data[::-1])

1
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


# 🧊 Boolean Masking ~ Filterring Data

### arr[arr>x]

In [ ]:
marks = np.array([90,91,92,93,94,95,96,97,98,99,100])
marks[marks>95]

array([ 96,  97,  98,  99, 100])

# 🧊 Reverse an Array

### np.flip( )

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
np.flip(arr)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

#  🧊 Non-Zero Operations

### np.nonzero(), np.count_nonzero()

np.nonzero()

In [ ]:
# Return the *indexes* of the elements that are non-zero

In [ ]:
arr = np.array([1,2,0,5,0,0,1,0,5])
print(np.nonzero(arr))
idx = np.nonzero(arr)
print(arr[idx])

(array([0, 1, 3, 6, 8]),)
[1 2 5 1 5]


In [ ]:
np.count_nonzero(arr) == len(arr[np.nonzero(arr)])

True

# 🧊 Shallow Copy VS Deep Copy

### a.view() vs a.copy()

In [ ]:
# Shallow Copy
a = np.array([1,2,3,4,5])
view_arr = a.view()
view_arr[0]=69
print("Original Array:",a)
print("Copied Array:",view_arr)

Original Array: [69  2  3  4  5]
Copied Array: [69  2  3  4  5]


In [ ]:
# Deep Copy
a = np.array([1,2,3,4,5])
copy_arr = a.copy()
copy_arr[0]=69
print("Original Array:",a)
print("Copied Array:",copy_arr)

Original Array: [1 2 3 4 5]
Copied Array: [69  2  3  4  5]


# 🧊 Basic Operations on Array

### np.max(). np.min(), np.argmax(), np.argmin(), np.sum(), np.mean(), np.std(), np.var()

In [ ]:
arr = np.array([1,-5,6,9,7,10,-2,5,6])
print(np.max(arr))
print(np.min(arr))

print(np.argmax(arr)) # returns index of the maximum value in an array
print(np.argmin(arr)) # returns index of the minimum value in an array

print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))

10
-5
5
1
37
4.111111111111111
4.771313456351975
22.765432098765434


Sum

In [ ]:
a = np.array([14,8,5,6])
b = np.array([2,4,5,1])
print(a+b,type(a+b))
print(a-b)
print(a*b)
print(a/b)
print(b**2)

[16 12 10  7] <class 'numpy.ndarray'>
[12  4  0  5]
[28 32 25  6]
[7. 2. 1. 6.]
[ 4 16 25  1]


In [ ]:
a.sum()

np.int64(33)

2D Array

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Array:\n", arr)

# Column-wise sum (axis=0)
print("Column-wise sum (axis=0):", np.sum(arr, axis=0))

# Row-wise sum (axis=1)
print("Row-wise sum  (axis=1):", np.sum(arr, axis=1))


Original Array:
 [[1 2 3]
 [4 5 6]]
Column-wise sum (axis=0): [5 7 9]
Row-wise sum  (axis=1): [ 6 15]


Multiplication

In [ ]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A * B)     # elementwise product
print("----------")
print(A @ B)     # matrix product
print("----------")
print(A.dot(B))  # another matrix product

[[2 0]
 [0 4]]
----------
[[5 4]
 [3 4]]
----------
[[5 4]
 [3 4]]


In [ ]:
temp = np.array([33.0,34.5,32.1,33,1,40.54])
np.mean(temp)

np.float64(29.02333333333333)

# 🧊 Generating random numbers

### np.random.randint( )

In [ ]:
# Random float between 0 and 1
print(np.random.rand())

# Random array of floats between 0 and 1 (4x3 Matrix)
print(np.random.rand(4,3))

# Random integer between 1 and 100
print(np.random.randint(1, 100))

# Random 'integer array' between 1 and 100
print(np.random.randint(1, 100, size=5))

# Random 'integer matrix' between 1 and 100
np.random.randint(1,100, size=(6,4))

0.180878464762804
[[0.9270132  0.62738627 0.75559825]
 [0.4985546  0.3258639  0.39705632]
 [0.04395865 0.57806952 0.88863141]
 [0.12145852 0.63191476 0.5929283 ]]
87
[28 55 14 11 28]


array([[ 2, 99, 64, 86],
       [79, 83, 95, 15],
       [27, 28, 51, 16],
       [93, 74,  3, 91],
       [68, 88, 12, 55],
       [70, 59,  6, 28]])

# 🧊 Unique Values

### np.unique( )

In [ ]:
# Returns an array of unique values

In [ ]:
a = np.array([1,1,2,2,2,3,3,3,4,4,4,5,5,6,7])
print(np.unique(a))

[1 2 3 4 5 6 7]


In [ ]:
# To return indexes of unique values
# return_index = True

In [ ]:
_,indices_list = np.unique(a, return_index=True)
# In Python _, means “I don’t care about this value”
print(indices_list)

[ 0  2  5  8 11 13 14]


In [ ]:
# To return counts
# return_counts=True

In [ ]:
_,occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[2 3 3 3 2 1 1]


# 🧊 Handling Missing Values

### np.isnan(), np.isinf(), np.nan_to_num(arr,nan = x), np.nan_to_num(arr,posinf = 999, neginf = -999)

In [ ]:
# np.isnan() returns boolean array
arr = np.array([1,np.nan,3,4,np.nan])
np.isnan(arr)

array([False,  True, False, False,  True])

In [ ]:
arr = np.array([1,np.nan,3,4,np.nan])
new_arr = np.nan_to_num(arr) # by default 0
print(new_arr)
new_arr = np.nan_to_num(arr,nan=69)
print(new_arr)

[1. 0. 3. 4. 0.]
[ 1. 69.  3.  4. 69.]


In [ ]:
arr = np.array([-1, 5, 3, np.inf, 0, 1, -np.inf])
np.isinf(arr)

array([False, False, False,  True, False, False,  True])

In [ ]:
arr = np.array([-1, 5, 3, np.inf, 0, 1, -np.inf])
new_arr = np.nan_to_num(arr,posinf=9999,neginf=-9999)
print(new_arr)

[-1.000e+00  5.000e+00  3.000e+00  9.999e+03  0.000e+00  1.000e+00
 -9.999e+03]
