In [ ]:
import numpy as np

In [ ]:
matrix = np.array(([1,2,4,7],
                   [1,0,1,0],
                   [3,5,6,7],
                   [1,9,4,7]))

# 🧊 1D Array to 2D Array

# np.reshape()

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
np.reshape(arr,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 🧊 Multiple 1D Array to single 2D Array

# np.vstack()

In [ ]:
arr = np.array([1,2,3])
brr = np.array([4,5,6])
crr = np.array([7,8,9])
np.vstack((arr,brr,crr))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 🧊 2D Array to 1D Array

### np.flatten( ), np.ravel( ), np.concatenate( ), np.hstack()

In [ ]:
# 2D Array to 1D Array
matrix.flatten() # shallow copy ~ No manipulation effect

array([1, 2, 4, 7, 1, 0, 1, 0, 3, 5, 6, 7, 1, 9, 4, 7])

In [ ]:
# 2D Array to 1D Array
matrix.ravel() # deep copy ~  manipulation effects

array([1, 2, 4, 7, 1, 0, 1, 0, 3, 5, 6, 7, 1, 9, 4, 7])

In [ ]:
matrix = np.array(([1,2,4,7],
                   [1,0,1,0],
                   [3,5,6,7],
                   [1,9,4,7]))
rvl = matrix.ravel()
flat = matrix.flatten()
print(rvl)
print(flat)
print("-----------------------")
flat[0]=999
print(flat)
print(matrix) # No change in Original Matrix
print("-----------------------")
rvl[0]=99
print(rvl)
print(matrix)

[1 2 4 7 1 0 1 0 3 5 6 7 1 9 4 7]
[1 2 4 7 1 0 1 0 3 5 6 7 1 9 4 7]
-----------------------
[999   2   4   7   1   0   1   0   3   5   6   7   1   9   4   7]
[[1 2 4 7]
 [1 0 1 0]
 [3 5 6 7]
 [1 9 4 7]]
-----------------------
[99  2  4  7  1  0  1  0  3  5  6  7  1  9  4  7]
[[99  2  4  7]
 [ 1  0  1  0]
 [ 3  5  6  7]
 [ 1  9  4  7]]


In [ ]:
# 2D Array to 1D
np.concatenate(matrix,axis=None)

array([99,  2,  4,  7,  1,  0,  1,  0,  3,  5,  6,  7,  1,  9,  4,  7])

In [ ]:
arr = np.array([1,2,3])
brr = np.array([4,5,6])
np.hstack((arr,brr)) # np.concatenate(arr,brr,axis=None)

array([1, 2, 3, 4, 5, 6])

# 🧊 Splitting

### np.split()

In [ ]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [0,9,7,1],
              [1,0,5,4]])
# Split into 2 along rows (axis=0)
print(np.split(a, 2, axis=0))
print("-----------------------------------------------")
# Split into 2 along columns (axis=1)
print(np.split(a, 2, axis=1))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[0, 9, 7, 1],
       [1, 0, 5, 4]])]
-----------------------------------------------
[array([[1, 2],
       [5, 6],
       [0, 9],
       [1, 0]]), array([[3, 4],
       [7, 8],
       [7, 1],
       [5, 4]])]


# 🧊 No. of rows & cols of a matrix

# matrix.size

In [ ]:
matrix = np.array(([1,2,4,7],
                   [1,0,1,0],
                   [3,5,6,7],
                   [1,9,4,7]))
matrix.shape

(4, 4)

# 🧊 Inserting Items

### np.insert()

In [ ]:
# Row wise insertion
matrix = np.array(([1,2,4,7],
                   [1,0,1,0],
                   [3,5,6,7],
                   [1,9,4,7]))
np.insert(matrix, 1, [99,69,89,59], axis=0)

array([[ 1,  2,  4,  7],
       [99, 69, 89, 59],
       [ 1,  0,  1,  0],
       [ 3,  5,  6,  7],
       [ 1,  9,  4,  7]])

In [ ]:
# Columnn wise insertion
matrix = np.array(([1,2,4,7],
                   [1,0,1,0],
                   [3,5,6,7],
                   [1,9,4,7]))
np.insert(matrix, 1, [99,69,89,59], axis=1)

array([[ 1, 99,  2,  4,  7],
       [ 1, 69,  0,  1,  0],
       [ 3, 89,  5,  6,  7],
       [ 1, 59,  9,  4,  7]])

# 🧊 Deleteing Items

### np.delete()

In [ ]:
# Row wise deleteion
matrix = np.array(([1,2,4,7],
                   [1,0,1,0],
                   [3,5,6,7],
                   [1,9,4,7]))
new_matrix = np.delete(matrix, 0, axis=0)
print(new_matrix)

[[1 0 1 0]
 [3 5 6 7]
 [1 9 4 7]]


In [ ]:
# Coloumn wise deleteion
matrix = np.array(([1,2,4,7],
                   [1,0,1,0],
                   [3,5,6,7],
                   [1,9,4,7]))
new_matrix = np.delete(matrix, 0, axis=1)
print(new_matrix)

[[2 4 7]
 [0 1 0]
 [5 6 7]
 [9 4 7]]


# 🧊 Matrix Reshape

### np.reshape( )

In [ ]:
matrix = np.array([1,2,3,4,5,6,7,8,9])
np.reshape(matrix,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 🧊 Transpose

### np.transpose(matrix) or, matrix.transpose( ), matrix.T

In [ ]:
matrix = np.array(([1,2,4,7],
                   [1,0,1,0],
                   [3,5,6,7],
                   [1,9,4,7]))

In [ ]:
np.transpose(matrix)

array([[1, 1, 3, 1],
       [2, 0, 5, 9],
       [4, 1, 6, 4],
       [7, 0, 7, 7]])

In [ ]:
matrix.transpose()

array([[1, 1, 3, 1],
       [2, 0, 5, 9],
       [4, 1, 6, 4],
       [7, 0, 7, 7]])

In [ ]:
matrix.T

array([[1, 1, 3, 1],
       [2, 0, 5, 9],
       [4, 1, 6, 4],
       [7, 0, 7, 7]])

# 🧊 Identity Matrix

### np.eye( )

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 🧊 Matrix Reverse

### np.flip( ), matrix[x]=np.flip(matrix[x]), matrix[:,x]=np.flip(matrix[:,x])

In [ ]:
matrix = np.array(([1,2,4,7],
                   [1,0,1,0],
                   [3,5,6,7],
                   [1,9,4,7]))

In [ ]:
np.flip(matrix)

array([[7, 4, 9, 1],
       [7, 6, 5, 3],
       [0, 1, 0, 1],
       [7, 4, 2, 1]])

In [ ]:
# Reverse row-wise
np.flip(matrix, axis=1)

array([[7, 4, 2, 1],
       [0, 1, 0, 1],
       [7, 6, 5, 3],
       [7, 4, 9, 1]])

In [ ]:
# Reverse column-wise
np.flip(matrix, axis=0)

array([[1, 9, 4, 7],
       [3, 5, 6, 7],
       [1, 0, 1, 0],
       [1, 2, 4, 7]])

In [ ]:
# Reverse a particular row
matrix = np.array(([1,2,4,7],
                   [1,0,1,0],
                   [3,5,6,7],
                   [1,9,4,7]))
matrix[3] = np.flip(matrix[3])
print(matrix)

[[1 2 4 7]
 [1 0 1 0]
 [3 5 6 7]
 [7 4 9 1]]


In [ ]:
# Reverse a particular column
matrix = np.array(([1,2,4,7],
                   [1,0,1,0],
                   [3,5,6,7],
                   [1,9,4,7]))
matrix[:,2] = np.flip(matrix[:,2])
print(matrix)

[[1 2 4 7]
 [1 0 6 0]
 [3 5 1 7]
 [1 9 4 7]]


# 🧊 Matrix Addition

### np.sum( )

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Array:\n", arr)

# Column-wise sum (axis=0)
print("Column-wise sum (axis=0):", np.sum(arr, axis=0))

# Row-wise sum (axis=1)
print("Row-wise sum  (axis=1):", np.sum(arr, axis=1))


Original Array:
 [[1 2 3]
 [4 5 6]]
Column-wise sum (axis=0): [5 7 9]
Row-wise sum  (axis=1): [ 6 15]


In [ ]:
# 2D NumPy array
x = np.array([
    [3.0, 7.5, 2.1],
    [9.8, 4.6, 5.2]
])

print("Array:\n", x)

print("\n-------------- Overall -----------------")
print("Max           :", np.max(x))
print("Min           :", np.min(x))
print("Index of max  :", np.argmax(x)) # Note: This is the index in the flattened array
print("Index of min  :", np.argmin(x)) # Note: This is the index in the flattened array
print("Mean          :", np.mean(x))
print("Median        :", np.median(x))
print("Variance      :", np.var(x))
print("Std Deviation :", np.std(x))

# ------------ Column-wise (axis=0) ---------------
# In NumPy, dim=0 corresponds to axis=0
print("\n---------- Column-wise (axis=0) ---------")
print("Max           :", np.max(x, axis=0))
print("Min           :", np.min(x, axis=0))
print("Index of max  :", np.argmax(x, axis=0))
print("Index of min  :", np.argmin(x, axis=0))
print("Mean          :", np.mean(x, axis=0))
print("Median        :", np.median(x, axis=0))
print("Variance      :", np.var(x, axis=0))
print("Std Deviation :", np.std(x, axis=0))

# ---------------- Row-wise (axis=1) ---------------
# In NumPy, dim=1 corresponds to axis=1
print("\n------------ Row-wise (axis=1) ----------")
print("Max           :", np.max(x, axis=1))
print("Min           :", np.min(x, axis=1))
print("Index of max  :", np.argmax(x, axis=1))
print("Index of min  :", np.argmin(x, axis=1))
print("Mean          :", np.mean(x, axis=1))
print("Median        :", np.median(x, axis=1))
print("Variance      :", np.var(x, axis=1))
print("Std Deviation :", np.std(x, axis=1))

Array:
 [[3.  7.5 2.1]
 [9.8 4.6 5.2]]

-------------- Overall -----------------
Max           : 9.8
Min           : 2.1
Index of max  : 3
Index of min  : 2
Mean          : 5.366666666666667
Median        : 4.9
Variance      : 6.848888888888891
Std Deviation : 2.6170381901854034

---------- Column-wise (axis=0) ---------
Max           : [9.8 7.5 5.2]
Min           : [3.  4.6 2.1]
Index of max  : [1 0 1]
Index of min  : [0 1 0]
Mean          : [6.4  6.05 3.65]
Median        : [6.4  6.05 3.65]
Variance      : [11.56    2.1025  2.4025]
Std Deviation : [3.4  1.45 1.55]

------------ Row-wise (axis=1) ----------
Max           : [7.5 9.8]
Min           : [2.1 4.6]
Index of max  : [1 0]
Index of min  : [2 1]
Mean          : [4.2        6.53333333]
Median        : [3.  5.2]
Variance      : [5.58       5.39555556]
Std Deviation : [2.36220236 2.32283352]
